// Auth
export const LOGOUT  = 'LOGOUT';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
export const GET_SESSION  = 'GET_SESSION';
export const SET_SESSION = 'SET_SESSION';

// Movies
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_NOW_PLAYING_MOVIES = 'FETCH_NOW_PLAYING_MOVIES';
export const FETCH_MOVIE_GENRES = 'FETCH_MOVIE_GENRES';

//TV Shows
export const FETCH_POPULAR_SHOWS = 'FETCH_POPULAR_SHOWS';
export const FETCH_TOP_RATED_SHOWS = 'FETCH_TOP_RATED_SHOWS';
export const FETCH_ON_THE_AIR_SHOWS = 'FETCH_ON_THE_AIR_SHOWS';
export const FETCH_ON_THE_AIR_TODAY_SHOWS = 'FETCH_ON_THE_AIR_TODAY_SHOWS';
export const FETCH_SHOW_GENRES = 'FETCH_SHOW_GENRES';