// Auth
export const LOGOUT  = 'LOGOUT';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const GET_TOKEN = 'GET_TOKEN';
export const SET_TOKEN = 'SET_TOKEN';
export const GET_SESSION  = 'GET_SESSION';
export const SET_SESSION = 'SET_SESSION';

// Movies
export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';
export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';
export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_NOW_PLAYING_MOVIES = 'FETCH_NOW_PLAYING_MOVIES';

//TV Shows
export const FETCH_POPULAR_SHOWS = 'FETCH_POPULAR_SHOWS';
export const FETCH_LATEST_SHOWS = 'FETCH_LATEST_SHOWS';
export const FETCH_UPCOMING_SHOWS = 'FETCH_UPCOMING_SHOWS';
export const FETCH_NOW_PLAYING_SHOWS = 'FETCH_NOW_PLAYING_SHOWS';